### ISSUE TITLE
Unable to load DLL 'avutil.56' error

### ISSUE THREAD

**Issue by srht** [radek-k/FFMediaToolkit#100]
I'm trying to use the library in asp.net web application that runs with .net framework 4.7.2. I set FFmpegLoader.FFmpegPath to the dll files that I downloaded win64 modes from https://github.com/BtbN/FFmpeg-Builds/releases My application is 64 bit. Then it gives Unable to load DLL 'avutil.56' error. How can I solve this?

**Comment by NurulloSulaymonov** [comment]
same with me

**Comment by NurulloSulaymonov** [comment]
@srht here is the solution https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/192#issuecomment-1018171060

**Comment by Ruslan-B** [comment]
@srht which release you downloaded? 
I guess for a while you have to stick to 4.4. As I updated foundation library for FFMediaToolkit just yesterday.

**Comment by Norc89** [comment]
When this is planned to be fixed ?

**Comment by radek-k** [comment]
I've updated the package.

**Comment by radek-k** [comment]
5.0

**Comment by radek-k** [comment]
Which FFmpeg build have you downloaded?
Try installing FFmpeg using apt, then set the FFmpegPath to "/usr/local/lib/"

**Comment by Norc89** [comment]
> Which FFmpeg build have you downloaded? Try installing FFmpeg using apt, then set the FFmpegPath to "/usr/local/lib/"

Is possible that we continue this conversation in private chat?

**Comment by Norc89** [comment]
> Which FFmpeg build have you downloaded? Try installing FFmpeg using apt, then set the FFmpegPath to "/usr/local/lib/"

I have try both builds gpl-shared and lgpl-shared. I really need to get this working on raspberry. I don't even know if is possible to get running dlls on Raspi.

**Comment by hey-red** [comment]
I think you need ARM build for RPI. Do you download right version?

**Comment by Ruslan-B** [comment]
RPI linux distributive has to have package manager in any normal linux version (if assembled by hand I would expect OP knows what do) - what could possible go wrong?

**Comment by tottaka** [comment]
Has anyone gotten this to work? I'm having the same exact issue. I installed ffmpeg from apt (ffmpeg is already the newest version (7:4.3.4-0+deb11u1+rpt1))

I ran `ldd /usr/bin/ffmpeg` which told me the .so files were located in "/lib/aarch64-linux-gnu/" so I tried that first, same error.

I then tried setting ffmpeg path "/usr/local/lib/" and still got the error.
I couldn't find the "Prefer 32-bit" option in VS2022 so I tried building for ARM64 which still gave me the same error.

Running command `file `which ffmpeg`` gives me:
`/usr/bin/ffmpeg: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=1e9e84ad62abcf8f99020bdcbf9b7d5a79e529a4, for GNU/Linux 3.7.0, stripped`

Running `ldd /usr/bin/ffmpeg | grep "avutil"` outputs:
        libavutil.so.56 => /lib/aarch64-linux-gnu/libavutil.so.56 (0x0000007f9289f000)

So maybe that's where the problem occurs? Is there a way to get version .57 instead of .56?

**Comment by hey-red** [comment]
@tottaka Your installed ffmpeg version is 4.3.4, but latest FFMediaToolkit works only with 5.x.x
Possible solutions:
* Add debian repository with newest ffmpeg(switch to testing or upgrade to next debian release).
* Build ffmpeg from sources or download binary packages for aarch64 and set full path to ffmpeg binaries(FFmpegLoader.FFmpegPath="/path/to/ffmpeg")
* Install old FFMediaToolkit package(not recommended)

**Comment by tottaka** [comment]
@hey-red I got it working by building ffmpeg 5.0 from source.
I did have to include build option `--enable-shared` otherwise the .so files were not generated. Also I think running `ldconfig`
made links to the libs in "/usr/local/lib" so I was able to set `FFmpegLoader.FFmpegPath` to that instead of the full path to ffmpeg.

It's a shame the default apt repository is using an outdated ffmpeg version...

Thank you!
