### ISSUE TITLE
support blazor

### ISSUE THREAD

**Issue by behroozbc** [radek-k/FFMediaToolkit#70]
hi 
I want use this nuget package in blazor but get this error 
please support blazor 
[FFToolKit.log](https://github.com/radek-k/FFMediaToolkit/files/6080707/FFToolKit.log)

**Comment by yodadude2003** [comment]
Unfortunately at this time I don't think blazor would be able to function with the library as it is.  The error you are receiving is being thrown because you are missing the native ffmpeg libraries.  If you want to encode video on the server side, I suppose it would work just fine, however if you want to encode video on the client side, you'll need to use some other WASM based wrapper or library.
